server:
  port: 8082
  servlet: "*.do"
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydata?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root