spring:
  datasource:
    read:
      jdbc-url: jdbc:mysql://localhost:3306/my_date_read?useUnicode=true&characterEncoding=utf8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
    write:
      jdbc-url:: jdbc:mysql://localhost:3306/my_date_write?useUnicode=true&characterEncoding=utf8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root